ahaw021 commented on 15 Apr 2017
My operating system is (include version):
windows 2012 r2
I installed Certbot with (certbot-auto, OS package manager, pip, etc):
pip
I ran this command and it produced this output:
certbot certonly
['--manual', '--expand', '-d', 'f5-site.firecube.xyz', '-d', 'f5-site4.firecube.xyz', '--preferred-challenges=dns']
Certbot's behavior differed from what I expected because:
Error
FileExistsError: [WinError 183] Cannot create a file when that file already exists: 'C:\etc\letsencrypt\renewal\f5-site.firecube.xyz.conf.new' -> 'C:\etc\letsencrypt\renewal\f5-site.firecube.xyz.conf'
Root Cause
On Unix, if dst exists and is a file, it will be replaced silently if the user has permission. The operation may fail on some Unix flavors if src and dst are on different filesystems. If successful, the renaming will be an atomic operation (this is a POSIX requirement). On Windows, if dst already exists, OSError will be raised even if it is a file.
Fix:
I replaced the the os.rename() functions with os.replace()
Storage.py - Lines 165 and 136
Reading the documentation this should not impact linux b
Here is a Certbot log showing the issue (if available):
Logs are stored in /var/log/letsencrypt by default. Feel free to redact domains, e-mail and IP addresses as you see fit.
Traceback (most recent call last):
File "c:\python37\Lib\runpy.py", line 193, in _run_module_as_main
"main", mod_spec)
File "c:\python37\Lib\runpy.py", line 85, in run_code
exec(code, run_globals)
File "C:\Certbot-Production\Scripts\certbot.exe_main.py", line 9, in
sys.exit(main())
File "c:\certbot-production\lib\site-packages\certbot\main.py", line 755, in main
return config.func(config, plugins)
File "c:\certbot-production\lib\site-packages\certbot\main.py", line 682, in certonly
lineage = _get_and_save_cert(le_client, config, domains, certname, lineage)
File "c:\certbot-production\lib\site-packages\certbot\main.py", line 77, in _get_and_save_cert
renewal.renew_cert(config, domains, le_client, lineage)
File "c:\certbot-production\lib\site-packages\certbot\renewal.py", line 306, in renew_cert
lineage.save_successor(prior_version, new_cert, new_key.pem, new_chain, config)
File "c:\certbot-production\lib\site-packages\certbot\storage.py", line 1100, in save_successor
self.lineagename, self.archive_dir, symlinks, cli_config)
File "c:\certbot-production\lib\site-packages\certbot\storage.py", line 158, in update_configuration
os.rename(temp_filename, config_filename)
FileExistsError: [WinError 183] Cannot create a file when that file already exists: 'C:\etc\letsencrypt\renewal\f5-site.firecube.xyz.conf.new' -> 'C:\etc\letsencrypt\renewal\f5-site.firecube.xyz.conf'
2