Member
bmw commented on 13 Apr 2019
https://github.com/certbot/certbot/blob/master/tests/letstest/scripts/test_sdists.sh is now broken on master on every system we test on in our test farm tests. Before #6932 landed, it worked, but afterwards it does not.
A snippet of the output from running the tests is:
certbot/tests/util_test.py .........................................................
certbot/tests/display/completer_test.py .....
certbot/tests/display/enhancements_test.py .....
certbot/tests/display/ops_test.py .........................................
certbot/tests/display/util_test.py ............................................

========================= 871 passed in 23.56 seconds ==========================
NameError: global name 'sys' is not defined
Please see the logfile '/tmp/tmpYaIPn2' for more details.
The last line about the logfile is from Certbot, but unfortunately the logfile doesn't exist after the process exits.
@adferrand, are you able to look into this? You can run the tests by cloning this repo into a directory named letsencrypt and then running the tests from just outside that directory (e.g. run letsencrypt/tests/letstest/scripts/test_sdists.sh).
Because this certainly needs be fixed before the next release, I'm not sure if we should land any more Windows security PRs until this is fixed. On the off chance we don't get this fixed in time, we'll need to revert #6932 and any PRs depending on it which will be every PR about Windows security. This includes some pretty massive changes and will generate a lot of conflicts with git so I'd personally rather see this resolved before trying to make more progress there.