EmersonBR commented on 3 Mar 2017
My operating system is (include version):
raspian 1.1 Pi
I installed Certbot with (certbot-auto, OS package manager, pip, etc):
?
I ran this command and it produced this output:
pi@hassbian:~ $ cd letsencrypt
pi@hassbian:~/letsencrypt $ ./letsencrypt-auto certonly --email xxxxxxx@gmail.com -d xxxxxxxxxxx.duckdns.org
Certbot's behavior differed from what I expected because:
Got an error:
Saving debug log to /var/log/letsencrypt/letsencrypt.log
Failed to find apache2ctl in PATH: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
How would you like to authenticate with the ACME CA?
1: Place files in webroot directory (webroot)
2: Spin up a temporary webserver (standalone)
Select the appropriate number [1-2] then [enter] (press 'c' to cancel): Traceback (most recent call last):
File "/home/pi/.local/share/letsencrypt/bin/letsencrypt", line 11, in
sys.exit(main())
File "/home/pi/.local/share/letsencrypt/local/lib/python2.7/site-packages/certbot/main.py", line 882, in main
return config.func(config, plugins)
File "/home/pi/.local/share/letsencrypt/local/lib/python2.7/site-packages/certbot/main.py", line 650, in obtain_cert
installer, auth = plug_sel.choose_configurator_plugins(config, plugins, "certonly")
File "/home/pi/.local/share/letsencrypt/local/lib/python2.7/site-packages/certbot/plugins/selection.py", line 190, in choose_configurator_plugins
authenticator = pick_authenticator(config, req_auth, plugins)
File "/home/pi/.local/share/letsencrypt/local/lib/python2.7/site-packages/certbot/plugins/selection.py", line 40, in pick_authenticator
config, default, plugins, question, (interfaces.IAuthenticator,))
File "/home/pi/.local/share/letsencrypt/local/lib/python2.7/site-packages/certbot/plugins/selection.py", line 82, in pick_plugin
plugin_ep = choose_plugin(list(six.itervalues(prepared)), question)
File "/home/pi/.local/share/letsencrypt/local/lib/python2.7/site-packages/certbot/plugins/selection.py", line 115, in choose_plugin
question, opts, help_label="More Info", force_interactive=True)
File "/home/pi/.local/share/letsencrypt/local/lib/python2.7/site-packages/certbot/display/util.py", line 120, in menu
code, selection = self._get_valid_int_ans(len(choices))
File "/home/pi/.local/share/letsencrypt/local/lib/python2.7/site-packages/certbot/display/util.py", line 392, in _get_valid_int_ans
ans = six.moves.input(input_msg)
KeyboardInterrupt
Here is a Certbot log showing the issue (if available):
Logs are stored in /var/log/letsencrypt by default. Feel free to redact domains, e-mail and IP addresses as you see fit.
I can't find the letsencryp log either. I am trying to install let's encrypt using Putty on my Raspberry Pi 3.
what to do? Thank you in advance for your help.