bazo commented on 28 Jul 2016
hi,
when trying to run certbot i get this error
this is the full log
Traceback (most recent call last):
  File "/usr/bin/certbot", line 9, in <module>
    load_entry_point('certbot==0.8.1', 'console_scripts', 'certbot')()
  File "build/bdist.linux-x86_64/egg/pkg_resources.py", line 348, in load_entry_point
  File "build/bdist.linux-x86_64/egg/pkg_resources.py", line 2311, in load_entry_point
  File "build/bdist.linux-x86_64/egg/pkg_resources.py", line 2025, in load
  File "/usr/lib/python2.7/dist-packages/certbot/main.py", line 18, in <module>
    from certbot import account
  File "/usr/lib/python2.7/dist-packages/certbot/account.py", line 15, in <module>
    from acme import messages
  File "/usr/lib/python2.7/dist-packages/acme/messages.py", line 4, in <module>
    from acme import challenges
  File "/usr/lib/python2.7/dist-packages/acme/challenges.py", line 10, in <module>
    import requests
  File "/usr/local/lib/python2.7/dist-packages/requests/__init__.py", line 53, in <module>
    from .packages.urllib3.contrib import pyopenssl
  File "/usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/contrib/pyopenssl.py", line 43, in <module>
    ssl.PROTOCOL_SSLv3: OpenSSL.SSL.SSLv3_METHOD,
AttributeError: 'module' object has no attribute 'PROTOCOL_SSLv3'
debian 8. i updated and upgraded my packages, certbot installed today
i believe ssl v3 shouldn't be used due to poodle attack.
can i fix this or workaround it somehow?
thank