toddjames commented on 8 Oct 2016
Currently, while following the dev docs or cloning the existing flaskr project on GitHub, it will not run in a Python 3 virtualenv. The error when running the cloned flaskr application is:
Traceback (most recent call last): File "/home/todd/flaskr/flask/examples/flaskr/env/lib/python3.5/site-packages/flask/_compat.py", line 33, in reraise raise value File "/home/todd/flaskr/flask/examples/flaskr/flaskr/__init__.py", line 1, in <module> from flaskr import app ImportError: cannot import name 'app'
This is the same error when following the docs to recreate the flaskr application. By modifying flaskr/__init__.py to include a relative import when using a Python 3 virtualenv, everything works fine.
That is, in flaskr/__init__.py, change:
from flaskr import app
to:
from .flaskr import app
(note the period)
At this point, I am still not comfortable contributing, nor do I know if this is the correct solution or if this has any implications for Python 2. Hence the issue, hoping someone else can confirm this is correct, or provide a better solution.