mattthieu commented on Oct 8, 2012
hello,
I believe cross_validation.cross_val_score does not work with
clf = svm.SVC(kernel='precomputed')
When I use them I get the error
scores = cross_validation.cross_val_score(clf, dists, lbls, cv=5)
File "/usr/lib/pymodules/python2.7/sklearn/cross_validation.py", line 838, in cross_val_score
for train, test in cv)
File "/usr/lib/pymodules/python2.7/joblib/parallel.py", line 409, in call
self.dispatch(function, args, kwargs)
File "/usr/lib/pymodules/python2.7/joblib/parallel.py", line 295, in dispatch
job = ImmediateApply(func, args, kwargs)
File "/usr/lib/pymodules/python2.7/joblib/parallel.py", line 101, in init
self.results = func(_args, *_kwargs)
File "/usr/lib/pymodules/python2.7/sklearn/cross_validation.py", line 785, in _cross_val_score
estimator.fit(X[train], y[train])
File "/usr/lib/pymodules/python2.7/sklearn/svm/base.py", line 197, in fit
raise ValueError("X.shape[0] should be equal to X.shape[1]")
ValueError: X.shape[0] should be equal to X.shape[1]
I suspect it is due to the argument of SVC which is a square similarity matrix for kernel = 'precomputed' and a rectangular matrix of points coordinates for other kernels.
Sorry I don't have time to go much deaper. Hope this helps.
Cheers