Can't catch error in gen.Task