diswest commented on 13 Feb 2017
Some of ensembling models in sklearn expect attributes "classes_" and "n_classes_" in used classifiers. But KerasClassifier don't have these attributes, so ensembles raise errors.
For example, when I've tried to use BaggingCassifier from sklearn with KerasClassifier I received an error:
Traceback (most recent call last):
  File "keras_sklearn_bug.py", line 19, in <module>
    print(ensemble.predict(X))
  File "virtualenvs/kaggle/lib/python3.6/site-packages/sklearn/ensemble/bagging.py", line 641, in predict
    predicted_probabilitiy = self.predict_proba(X)
  File "virtualenvs/kaggle/lib/python3.6/site-packages/sklearn/ensemble/bagging.py", line 687, in predict_proba
    for i in range(n_jobs))
  File "virtualenvs/kaggle/lib/python3.6/site-packages/sklearn/externals/joblib/parallel.py", line 758, in __call__
    while self.dispatch_one_batch(iterator):
  File "virtualenvs/kaggle/lib/python3.6/site-packages/sklearn/externals/joblib/parallel.py", line 608, in dispatch_one_batch
    self._dispatch(tasks)
  File "virtualenvs/kaggle/lib/python3.6/site-packages/sklearn/externals/joblib/parallel.py", line 571, in _dispatch
    job = self._backend.apply_async(batch, callback=cb)
  File "virtualenvs/kaggle/lib/python3.6/site-packages/sklearn/externals/joblib/_parallel_backends.py", line 109, in apply_async
    result = ImmediateResult(func)
  File "virtualenvs/kaggle/lib/python3.6/site-packages/sklearn/externals/joblib/_parallel_backends.py", line 326, in __init__
    self.results = batch()
  File "virtualenvs/kaggle/lib/python3.6/site-packages/sklearn/externals/joblib/parallel.py", line 131, in __call__
    return [func(*args, **kwargs) for func, args, kwargs in self.items]
  File "virtualenvs/kaggle/lib/python3.6/site-packages/sklearn/externals/joblib/parallel.py", line 131, in <listcomp>
    return [func(*args, **kwargs) for func, args, kwargs in self.items]
  File "virtualenvs/kaggle/lib/python3.6/site-packages/sklearn/ensemble/bagging.py", line 134, in _parallel_predict_proba
    if n_classes == len(estimator.classes_):
AttributeError: 'KerasClassifier' object has no attribute 'classes_'
There is way to reproduce:
https://gist.github.com/diswest/8a92d317192726694d3fdd8373201211