gamboviol commented on 8 Jul 2015
I just cloned f817e2e and see this error when running examples/lstm_text_generation.py:
Iteration 1
Epoch 0
Traceback (most recent call last):
      File "lstm_text_generation.py", line 76, in <module>
        model.fit(X, y, batch_size=128, nb_epoch=1)
      File "build/bdist.macosx-10.10-intel/egg/keras/models.py", line 371, in fit
      File "build/bdist.macosx-10.10-intel/egg/keras/models.py", line 135, in _fit
      File "/Library/Python/2.7/site-packages/theano/compile/function_module.py", line 588, in __call__
        self.fn.thunks[self.fn.position_of_error])
      File "/Library/Python/2.7/site-packages/theano/compile/function_module.py", line 579, in __call__
outputs = self.fn()
      File "/Library/Python/2.7/site-packages/theano/gof/op.py", line 632, in rval
        r = p(n, [x[0] for x in i], o)
      File "/Library/Python/2.7/site-packages/theano/sandbox/cuda/basic_ops.py", line 2223, in perform
        out[0] = x.reshape(tuple(shp))
ValueError: size must remain unchanged, changed from 7552 to -59
Apply node that caused the error: GpuReshape{2}(GpuElemwise{add,no_inplace}.0, MakeVector.0)
Inputs shapes: [(128, 59), (2,)]
Inputs strides: [(59, 1), (8,)]
Inputs types: [CudaNdarrayType(float32, matrix), TensorType(int64, vector)]
If I revert to 1857a6a it runs fine. Did something get broken in between?