Caligatio commented on 16 Jun 2018
Steps to reproduce the problem:
Create an addon using the "done" event
Start mitmdump or mitmproxy with your addon specified using -s
Exit mitmproxy/mitmdump
Any other comments? What have you tried so far?
Here's a test addon that illustrates the problem:
class TestAddon():
    def done(self):
        print('Hello, World!')

addons = [
    TestAddon()
]
I am forced to use mitmproxy 3.X as we still use Ubuntu Xenial extensively across our infrastructure which uses Python 3.5. The below system dump reflects a VM I spun up to test this in isolation. This problem has been fixed in 4.X but it would be really great if it could be backported to 3.X as this is a killer bug for me (my add-on finalizes an output file in "done" and worked great in 2.X).
System information
Mitmproxy: 3.0.4
Python: 3.6.5
OpenSSL: OpenSSL 1.1.0h 27 Mar 2018
Platform: Linux-4.15.0-23-generic-x86_64-with-Ubuntu-18.04-bionic