rvernica commented on Feb 25, 2017
On one hand, I am using requests to access a web service in the local network. On the other hand, I access a SMTP server outside the network through a proxy. Once I do socks.wrapmodule(smtplib), requests starts using the proxy as well. Here is an example:
> python
Python 2.7.13 (default, Jan 13 2017, 10:15:16) 
[GCC 6.3.1 20161221 (Red Hat 6.3.1-1)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import requests
>>> requests.get('http://127.0.0.1:8000')
<Response [400]>
>>> import socks
>>> socks.setdefaultproxy(socks.PROXY_TYPE_HTTP, '...', 8088)
>>> requests.get('http://127.0.0.1:8000')
<Response [400]>
>>> import smtplib
>>> socks.wrapmodule(smtplib)
>>> requests.get('http://127.0.0.1:8000')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/vernica/.local/lib/python2.7/site-packages/requests/api.py", line 70, in get
    return request('get', url, params=params, **kwargs)
  File "/home/vernica/.local/lib/python2.7/site-packages/requests/api.py", line 56, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/vernica/.local/lib/python2.7/site-packages/requests/sessions.py", line 475, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/vernica/.local/lib/python2.7/site-packages/requests/sessions.py", line 596, in send
    r = adapter.send(request, **kwargs)
  File "/home/vernica/.local/lib/python2.7/site-packages/requests/adapters.py", line 423, in send
    timeout=timeout
  File "/home/vernica/.local/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py", line 595, in urlopen
    chunked=chunked)
  File "/home/vernica/.local/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py", line 363, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib64/python2.7/httplib.py", line 1042, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib64/python2.7/httplib.py", line 1082, in _send_request
    self.endheaders(body)
  File "/usr/lib64/python2.7/httplib.py", line 1038, in endheaders
    self._send_output(message_body)
  File "/usr/lib64/python2.7/httplib.py", line 882, in _send_output
    self.send(msg)
  File "/usr/lib64/python2.7/httplib.py", line 844, in send
    self.connect()
  File "/home/vernica/.local/lib/python2.7/site-packages/requests/packages/urllib3/connection.py", line 167, in connect
    conn = self._new_conn()
  File "/home/vernica/.local/lib/python2.7/site-packages/requests/packages/urllib3/connection.py", line 142, in _new_conn
    (self.host, self.port), self.timeout, **extra_kw)
  File "/home/vernica/.local/lib/python2.7/site-packages/requests/packages/urllib3/util/connection.py", line 88, in create_connection
    sock.connect(sa)
  File "/home/vernica/.local/lib/python2.7/site-packages/socks.py", line 780, in connect
    negotiate(self, dest_addr, dest_port)
  File "/home/vernica/.local/lib/python2.7/site-packages/socks.py", line 700, in _negotiate_HTTP
    raise HTTPError(error)
socks.HTTPError: 503: Service Unavailable

>>> requests.__version__
'2.11.1'
>>> socks.__version__
'1.6.4'